export enum ERROR_CODES {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',

  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',

  WHATSAPP_CONFIG_CONFLICT = 'WHATSAPP_CONFIG_CONFLICT',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
}
